const emojiToWord = {
  '😀': 'grinning',
  '😃': 'smile',
  '😄': 'happy',
  '😁': 'grin',
  '😆': 'laughing',
  '😅': 'sweat smile',
  '🤣': 'rolling on the floor laughing',
  '😂': 'tears of joy',
  '🙂': 'slightly smiling',
  '🙃': 'upside down',
  '😉': 'wink',
  '😊': 'blush',
  '😇': 'angel',
  '🥰': 'hearts',
  '😍': 'heart eyes',
  '🤩': 'star struck',
  '😘': 'kiss',
  '😗': 'kissing',
  '😚': 'kissing closed eyes',
  '😙': 'kissing smiling eyes',
  '🥲': 'tears of joy',
  '😋': 'yum',
  '😛': 'tongue out',
  '😜': 'winking tongue',
  '🤪': 'crazy',
  '😝': 'squinting tongue',
  '🤑': 'money mouth',
  '🤗': 'hugging',
  '🤭': 'hand over mouth',
  '🤫': 'shushing',
  '🤔': 'thinking',
  '🤐': 'zipper mouth',
  '🤨': 'raised eyebrow',
  '😐': 'neutral',
  '😑': 'expressionless',
  '😶': 'no mouth',
  '😏': 'smirk',
  '😒': 'unamused',
  '🙄': 'eye roll',
  '😬': 'grimacing',
  '🤥': 'lying',
  '😌': 'relieved',
  '😔': 'pensive',
  '😪': 'sleepy',
  '🤤': 'drooling',
  '😴': 'sleeping',
  '😷': 'mask',
  '🤒': 'sick',
  '🤕': 'bandage',
  '🤢': 'nauseated',
  '🤮': 'vomiting',
  '🤧': 'sneezing',
  '🥵': 'hot',
  '🥶': 'cold',
  '🥴': 'dizzy',
  '😵': 'dizzy face',
  '🤯': 'mind blown',
  '🤠': 'cowboy',
  '🥳': 'party',
  '🥸': 'disguise',
  '😎': 'cool',
  '🤓': 'nerd',
  '🧐': 'monocle',
  '😕': 'confused',
  '😟': 'worried',
  '🙁': 'frown',
  '☹️': 'frowning',
  '😮': 'wow',
  '😯': 'surprised',
  '😲': 'astonished',
  '😳': 'flushed',
  '🥺': 'pleading',
  '😦': 'frowning mouth',
  '😧': 'anguished',
  '😨': 'fearful',
  '😰': 'anxious sweat',
  '😥': 'sad sweat',
  '😢': 'crying',
  '😭': 'sobbing',
  '😱': 'screaming',
  '😖': 'confounded',
  '😣': 'persevering',
  '😞': 'disappointed',
  '😓': 'downcast sweat',
  '😩': 'weary',
  '😫': 'tired',
  '🥱': 'yawning',
  '😤': 'triumph',
  '😡': 'angry',
  '😠': 'rage',
  '🤬': 'cursing',
  '😈': 'devil',
  '👿': 'angry devil',
  '💀': 'skull',
  '☠️': 'skull and crossbones',
  '💩': 'poop',
  '🤡': 'clown',
  '👹': 'ogre',
  '👺': 'goblin',
  '👻': 'ghost',
  '👽': 'alien',
  '👾': 'space invader',
  '🤖': 'robot',
  '😺': 'cat smile',
  '😸': 'cat grin',
  '😹': 'cat tears of joy',
  '😻': 'cat heart eyes',
  '😼': 'cat smirk',
  '😽': 'cat kiss',
  '🙀': 'cat scream',
  '😿': 'cat crying',
  '😾': 'cat pouting',
  '❤️': 'red heart',
  '🧡': 'orange heart',
  '💛': 'yellow heart',
  '💚': 'green heart',
  '💙': 'blue heart',
  '💜': 'purple heart',
  '🖤': 'black heart',
  '🤍': 'white heart',
  '🤎': 'brown heart',
  '💔': 'broken heart',
  '❣️': 'heart exclamation',
  '💕': 'two hearts',
  '💞': 'revolving hearts',
  '💓': 'beating heart',
  '💗': 'growing heart',
  '💖': 'sparkling heart',
  '💘': 'cupid heart',
  '💝': 'heart box',
  '💟': 'heart decoration',
  '☮️': 'peace',
  '✝️': 'cross',
  '☪️': 'star and crescent',
  '🕉️': 'om',
  '☸️': 'dharma wheel',
  '✡️': 'star of david',
  '🔯': 'six pointed star',
  '🕎': 'menorah',
  '☯️': 'yin yang',
  '☦️': 'orthodox cross',
  '🛐': 'place of worship',
  '⛎': 'ophiuchus',
  '♈': 'aries',
  '♉': 'taurus',
  '♊': 'gemini',
  '♋': 'cancer',
  '♌': 'leo',
  '♍': 'virgo',
  '♎': 'libra',
  '♏': 'scorpio',
  '♐': 'sagittarius',
  '♑': 'capricorn',
  '♒': 'aquarius',
  '♓': 'pisces',
  '🆔': 'id',
  '⚛️': 'atom',
  '🉑': 'accept',
  '☢️': 'radioactive',
  '☣️': 'biohazard',
  '📴': 'mobile off',
  '📳': 'vibration',
  '🈶': 'not free',
  '🈚': 'free',
  '🈸': 'application',
  '🈺': 'open for business',
  '🈷️': 'monthly',
  '✴️': 'eight pointed star',
  '🆚': 'versus',
  '💮': 'white flower',
  '🉐': 'bargain',
  '㊙️': 'secret',
  '㊗️': 'congratulations',
  '🈴': 'passing grade',
  '🈵': 'no vacancy',
  '🈹': 'discount',
  '🈲': 'prohibited',
  '🅰️': 'a button',
  '🅱️': 'b button',
  '🆎': 'ab button',
  '🆑': 'cl button',
  '🅾️': 'o button',
  '🆘': 'sos',
  '❌': 'cross mark',
  '⭕': 'circle',
  '🛑': 'stop',
  '⛔': 'no entry',
  '📛': 'name badge',
  '🚫': 'prohibited',
  '💯': 'hundred',
  '💢': 'anger',
  '♨️': 'hot springs',
  '🚷': 'no pedestrians',
  '🚯': 'no littering',
  '🚳': 'no bicycles',
  '🚱': 'non potable water',
  '🔞': 'underage',
  '📵': 'no mobile',
  '🚭': 'no smoking',
  '❗': 'exclamation',
  '❕': 'exclamation mark',
  '❓': 'question',
  '❔': 'question mark',
  '‼️': 'double exclamation',
  '⁉️': 'question exclamation',
  '🔅': 'dim',
  '🔆': 'bright',
  '〽️': 'part alternation',
  '⚠️': 'warning',
  '🚸': 'children crossing',
  '🔱': 'trident',
  '⚜️': 'fleur de lis',
  '🔰': 'beginner',
  '♻️': 'recycling',
  '✅': 'check mark',
  '🈯': 'reserved',
  '💹': 'chart increasing',
  '❇️': 'sparkle',
  '✳️': 'eight spoked asterisk',
  '❎': 'cross mark button',
  '🌐': 'globe',
  '💠': 'diamond shape',
  'Ⓜ️': 'metro',
  '🌀': 'cyclone',
  '💤': 'zzz',
  '🏧': 'atm',
  '🚾': 'water closet',
  '♿': 'wheelchair',
  '🅿️': 'parking',
  '🈳': 'vacancy',
  '🈂️': 'service charge',
  '🛂': 'passport control',
  '🛃': 'customs',
  '🛄': 'baggage claim',
  '🛅': 'left luggage',
  '🚹': 'men',
  '🚺': 'women',
  '🚼': 'baby',
  '⚧️': 'transgender',
  '🚻': 'restroom',
  '🚮': 'litter',
  '🎦': 'cinema',
  '📶': 'signal',
  '🈁': 'here',
  '🔣': 'symbols',
  'ℹ️': 'information',
  '🔤': 'abc',
  '🔡': 'abcd',
  '🔠': 'capitals',
  '🆖': 'ng',
  '🆗': 'ok',
  '🆙': 'up',
  '🆒': 'cool',
  '🆕': 'new',
  '🆓': 'free',
  '0️⃣': 'zero',
  '1️⃣': 'one',
  '2️⃣': 'two',
  '3️⃣': 'three',
  '4️⃣': 'four',
  '5️⃣': 'five',
  '6️⃣': 'six',
  '7️⃣': 'seven',
  '8️⃣': 'eight',
  '9️⃣': 'nine',
  '🔟': 'ten',
  '👍': 'thumbs up',
  '👎': 'thumbs down',
  '👋': 'wave',
  '🤚': 'raised hand',
  '🖐️': 'hand with fingers',
  '✋': 'raised hand',
  '🖖': 'vulcan salute',
  '👌': 'ok hand',
  '🤌': 'pinched fingers',
  '🤏': 'pinching hand',
  '✌️': 'peace',
  '🤞': 'crossed fingers',
  '🤟': 'love you',
  '🤘': 'rock on',
  '🤙': 'call me',
  '👈': 'backhand left',
  '👉': 'backhand right',
  '👆': 'backhand up',
  '🖕': 'middle finger',
  '👇': 'backhand down',
  '☝️': 'index up',
  '✊': 'raised fist',
  '👊': 'fist bump',
  '🤛': 'left fist',
  '🤜': 'right fist',
  '👏': 'clapping',
  '🙌': 'raising hands',
  '👐': 'open hands',
  '🤲': 'palms together',
  '🤝': 'handshake',
  '🙏': 'pray',
  '✍️': 'writing',
  '💅': 'nail polish',
  '🤳': 'selfie',
  '💪': 'muscle',
  '🦾': 'mechanical arm',
  '🦿': 'mechanical leg',
  '🦵': 'leg',
  '🦶': 'foot',
  '👂': 'ear',
  '🦻': 'ear with hearing aid',
  '👃': 'nose',
  '🧠': 'brain',
  '🫀': 'anatomical heart',
  '🫁': 'lungs',
  '🦷': 'tooth',
  '🦴': 'bone',
  '👀': 'eyes',
  '👁️': 'eye',
  '👅': 'tongue',
  '👄': 'mouth',
  '🔥': 'fire',
  '💧': 'droplet',
  '💦': 'sweat droplets',
  '🌊': 'wave',
  '🎉': 'party popper',
  '🎊': 'confetti',
  '🎈': 'balloon',
  '🎁': 'gift',
  '🏆': 'trophy',
  '🥇': 'gold medal',
  '🥈': 'silver medal',
  '🥉': 'bronze medal',
  '⚽': 'soccer ball',
  '⚾': 'baseball',
  '🥎': 'softball',
  '🏀': 'basketball',
  '🏐': 'volleyball',
  '🏈': 'football',
  '🏉': 'rugby',
  '🎾': 'tennis',
  '🥏': 'flying disc',
  '🎳': 'bowling',
  '🏏': 'cricket',
  '🏑': 'field hockey',
  '🏒': 'ice hockey',
  '🥍': 'lacrosse',
  '🏓': 'ping pong',
  '🏸': 'badminton',
  '🥊': 'boxing glove',
  '🥋': 'martial arts',
  '🥅': 'goal',
  '⛳': 'flag in hole',
  '⛸️': 'ice skate',
  '🎣': 'fishing pole',
  '🤿': 'diving mask',
  '🎽': 'running shirt',
  '🎿': 'skis',
  '🛷': 'sled',
  '🥌': 'curling stone',
  '🎯': 'bullseye',
  '🪀': 'yo-yo',
  '🪁': 'kite',
  '🎱': 'pool ball',
  '🔮': 'crystal ball',
  '🪄': 'magic wand',
  '🧿': 'nazar amulet',
  '🎮': 'video game',
  '🕹️': 'joystick',
  '🎰': 'slot machine',
  '🎲': 'dice',
  '🧩': 'puzzle piece',
  '🧸': 'teddy bear',
  '🪅': 'pinata',
  '🪆': 'nesting dolls',
  '♠️': 'spade',
  '♥️': 'heart suit',
  '♦️': 'diamond suit',
  '♣️': 'club suit',
  '♟️': 'chess pawn',
  '🃏': 'joker',
  '🀄': 'mahjong',
  '🎴': 'flower cards',
  '🎭': 'performing arts',
  '🖼️': 'framed picture',
  '🎨': 'artist palette',
  '🧵': 'thread',
  '🪡': 'sewing needle',
  '🧶': 'yarn',
  '🪢': 'knot',
  '🍕': 'pizza',
  '🍔': 'burger',
  '🍟': 'fries',
  '🌭': 'hot dog',
  '🍿': 'popcorn',
  '🧈': 'butter',
  '🧂': 'salt',
  '🥚': 'egg',
  '🍳': 'cooking',
  '🧇': 'waffle',
  '🥞': 'pancakes',
  '🧀': 'cheese',
  '🍖': 'meat',
  '🍗': 'poultry',
  '🥩': 'steak',
  '🥓': 'bacon',
  '🌮': 'taco',
  '🌯': 'burrito',
  '🥙': 'stuffed flatbread',
  '🥘': 'paella',
  '🍲': 'pot of food',
  '🥣': 'bowl with spoon',
  '🥗': 'salad',
  '🥫': 'canned food',
  '🍱': 'bento',
  '🍘': 'rice cracker',
  '🍙': 'rice ball',
  '🍚': 'cooked rice',
  '🍛': 'curry',
  '🍜': 'steaming bowl',
  '🍝': 'spaghetti',
  '🍠': 'roasted sweet potato',
  '🍢': 'oden',
  '🍣': 'sushi',
  '🍤': 'fried shrimp',
  '🍥': 'fish cake',
  '🥮': 'moon cake',
  '🍡': 'dango',
  '🥟': 'dumpling',
  '🥠': 'fortune cookie',
  '🥡': 'takeout box',
  '🦀': 'crab',
  '🦞': 'lobster',
  '🦐': 'shrimp',
  '🦑': 'squid',
  '🦪': 'oyster',
  '🍦': 'ice cream',
  '🍧': 'shaved ice',
  '🍨': 'ice cream',
  '🍩': 'donut',
  '🍪': 'cookie',
  '🎂': 'birthday cake',
  '🍰': 'cake',
  '🧁': 'cupcake',
  '🥧': 'pie',
  '🍫': 'chocolate',
  '🍬': 'candy',
  '🍭': 'lollipop',
  '🍮': 'custard',
  '🍯': 'honey',
  '🍼': 'baby bottle',
  '🥛': 'milk',
  '☕': 'coffee',
  '🫖': 'teapot',
  '🍵': 'tea',
  '🍶': 'sake',
  '🍾': 'champagne',
  '🍷': 'wine',
  '🍸': 'cocktail',
  '🍹': 'tropical drink',
  '🍺': 'beer',
  '🍻': 'beers',
  '🥂': 'clinking glasses',
  '🥃': 'tumbler',
  '🥤': 'cup with straw',
  '🧋': 'bubble tea',
  '🧃': 'juice box',
  '🧉': 'mate',
  '🧊': 'ice',

  '🫠': 'melting face',
  '🫡': 'saluting face',
  '🫢': 'gasping face',
  '🫣': 'peeking face',
  '🫤': 'face with diagonal mouth',
  '🫥': 'dotted line face',
  '🫨': 'shaking face',
  '🥹': 'holding back tears',
  '🫶': 'heart hands',
  '🫰': 'money gesture',
  '🫷': 'left pushing hand',
  '🫸': 'right pushing hand',
  '🫳': 'palm down hand',
  '🫴': 'palm up hand',
  '🫱': 'rightward hand',
  '🫲': 'leftward hand',

  // New hearts
  '🩷': 'pink heart',
  '🩵': 'light blue heart',
  '🩶': 'gray heart',

  // Animals and nature
  '🦭': 'seal',
  '🪿': 'goose',
  '🦤': 'dodo',
  '🦫': 'beaver',
  '🦭': 'seal',
  '🦦': 'otter',
  '🦨': 'skunk',
  '🦩': 'flamingo',
  '🦮': 'guide dog',
  '🐕‍🦺': 'service dog',
  '🐈‍⬛': 'black cat',
  '🪿': 'goose',
  '🪱': 'worm',
  '🪰': 'fly',
  '🪳': 'cockroach',
  '🪲': 'beetle',
  '🪶': 'feather',
  '🪸': 'coral',
  '🪷': 'lotus',
  '🪻': 'hyacinth',
  '🪴': 'potted plant',

  // Food and drink (newer)
  '🫛': 'pea pod',
  '🫘': 'beans',
  '🫕': 'fondue',
  '🫓': 'flatbread',
  '🧆': 'falafel',
  '🫔': 'tamale',
  '🧄': 'garlic',
  '🧅': 'onion',
  '🫐': 'blueberries',
  '🫒': 'olive',
  '🫚': 'ginger',
  '🫛': 'peas',
  '🧇': 'waffle',
  '🧋': 'bubble tea',
  '🫗': 'pouring liquid',
  '🧃': 'juice box',
  '🧉': 'mate drink',
  '🧊': 'ice cube',

  // Gestures and body
  '🦰': 'red hair',
  '🦱': 'curly hair',
  '🦳': 'white hair',
  '🦲': 'bald',
  '🫦': 'biting lip',
  '🩸': 'blood drop',
  '🩹': 'adhesive bandage',
  '🩼': 'crutch',
  '🦽': 'manual wheelchair',
  '🦼': 'motorized wheelchair',
  '🩻': 'x-ray',

  // Clothing & accessories
  '🧢': 'cap',
  '🪖': 'military helmet',
  '🧣': 'scarf',
  '🧤': 'gloves',
  '🧥': 'coat',
  '🧦': 'socks',
  '🥾': 'hiking boot',
  '🥿': 'flat shoe',
  '👗': 'dress',
  '👕': 'tshirt',
  '🩲': 'briefs',
  '🩳': 'shorts',
  '🩴': 'flip flops',
  '🪮': 'comb',
  '🪭': 'folding fan',
  '🕶️': 'sunglasses',

  // Travel and places
  '🛻': 'pickup truck',
  '🚛': 'truck',
  '🛞': 'wheel',
  '🛺': 'auto rickshaw',
  '🛩️': 'small airplane',
  '🪂': 'parachute',
  '🛸': 'flying saucer',
  '🚀': 'rocket',
  '🛰️': 'satellite',
  '🛸': 'ufo',
  '🪐': 'planet',
  '🌌': 'milky way',
  '🪨': 'rock',
  '🪵': 'wood',
  '🛖': 'hut',
  '🛕': 'hindu temple',
  '🕌': 'mosque',
  '🕋': 'kaaba',
  '🪣': 'bucket',
  '🪠': 'plunger',

  // Objects
  '🪩': 'mirror ball',
  '🪞': 'mirror',
  '🪟': 'window',
  '🪑': 'chair',
  '🛋️': 'sofa',
  '🛏️': 'bed',
  '🪤': 'mouse trap',
  '🪒': 'razor',
  '🪡': 'needle',
  '🪢': 'knot',
  '🪫': 'low battery',
  '🪩': 'disco ball',
  '🪪': 'id card',
  '🪫': 'low battery',
  '🪤': 'mouse trap',
  '🧯': 'fire extinguisher',
  '🧰': 'toolbox',
  '🪓': 'axe',

  // Technology and media
  '🖲️': 'trackball',
  '🧭': 'compass',
  '🕰️': 'mantel clock',
  '🪫': 'low battery',
  '🪩': 'mirror ball',
  '📸': 'camera flash',
  '📹': 'video camera',
  '🧮': 'abacus',
  '🧾': 'receipt',
  '🪙': 'coin',
  '🪟': 'window',
  '🪣': 'bucket',

  // Symbols and weather
  '🌀': 'cyclone',
  '🌪️': 'tornado',
  '🌫️': 'fog',
  '🫧': 'bubbles',
  '🌡️': 'thermometer',
  '🌦️': 'sun behind rain cloud',
  '🌨️': 'snow cloud',
  '🌩️': 'lightning cloud',
  '🌈': 'rainbow',
  '🪹': 'empty nest',
  '🪺': 'nest',
  
  // Miscellaneous
  '🪵': 'wood',
  '🪶': 'feather',
  '🪿': 'goose',
  '🪼': 'jellyfish',
  '🪻': 'hyacinth',
  '🪺': 'nest with eggs',
  '🪹': 'empty nest',
  '🪨': 'rock',
  '🪵': 'log',
  '🪄': 'magic wand',
  '🪆': 'nesting dolls',
  '🪅': 'piñata',
  '🪭': 'folding fan',
  '🪮': 'comb',
  '🪯': 'khanda',

  // Hand-based gestures 
  '🫱🏽': 'rightward hand',
  '🫲🏿': 'leftward hand',
  '🫶🏻': 'heart hands',

  // Flags 
  '🏳️': 'white flag',
  '🏴': 'black flag',
  '🏳️‍🌈': 'rainbow flag',
  '🏳️‍⚧️': 'transgender flag',
  '🇮🇳': 'india flag',
  '🇺🇸': 'usa flag',
  '🇫🇷': 'france flag',
  '🇯🇵': 'japan flag',
  '🇨🇦': 'canada flag',
  '🇩🇪': 'germany flag',
  '🇬🇧': 'uk flag',

};


module.exports = emojiToWord;