export const emojiToWord: Record<string, string[]> = {
  '😀': ['grinning'],
  '😃': ['smile', 'happy'],
  '😄': ['happy', 'smile'],
  '😁': ['grin'],
  '😆': ['laughing'],
  '😅': ['sweat smile'],
  '🤣': ['rolling on the floor laughing', 'rofl'],
  '😂': ['tears of joy', 'lol'],
  '🙂': ['slightly smiling'],
  '🙃': ['upside down'],
  '😉': ['wink'],
  '😊': ['blush', 'smile'],
  '😇': ['angel'],
  '🥰': ['hearts', 'love'],
  '😍': ['heart eyes', 'love'],
  '🤩': ['star struck'],
  '😘': ['kiss'],
  '😗': ['kissing'],
  '😚': ['kissing closed eyes'],
  '😙': ['kissing smiling eyes'],
  '🥲': ['tears of joy'],
  '😋': ['yum'],
  '😛': ['tongue out'],
  '😜': ['winking tongue', 'crazy'],
  '🤪': ['crazy'],
  '😝': ['squinting tongue'],
  '🤑': ['money mouth'],
  '🤗': ['hugging'],
  '🤭': ['hand over mouth'],
  '🤫': ['shushing', 'quiet'],
  '🤔': ['thinking', 'hmm'],
  '🤐': ['zipper mouth', 'shut up'],
  '🤨': ['raised eyebrow'],
  '😐': ['neutral'],
  '😑': ['expressionless'],
  '😶': ['no mouth'],
  '😏': ['smirk'],
  '😒': ['unamused'],
  '🙄': ['eye roll'],
  '😬': ['grimacing'],
  '🤥': ['lying'],
  '😌': ['relieved'],
  '😔': ['pensive', 'sad'],
  '😪': ['sleepy'],
  '🤤': ['drooling'],
  '😴': ['sleeping'],
  '😷': ['mask'],
  '🤒': ['sick'],
  '🤕': ['bandage'],
  '🤢': ['nauseated'],
  '🤮': ['vomiting', 'puke'],
  '🤧': ['sneezing'],
  '🥵': ['hot'],
  '🥶': ['cold'],
  '🥴': ['dizzy', 'drunk'],
  '😵': ['dizzy face'],
  '🤯': ['mind blown'],
  '🤠': ['cowboy'],
  '🥳': ['party'],
  '🥸': ['disguise'],
  '😎': ['cool'],
  '🤓': ['nerd'],
  '🧐': ['monocle'],
  '😕': ['confused'],
  '😟': ['worried'],
  '🙁': ['frown'],
  '☹️': ['frowning'],
  '😮': ['wow'],
  '😯': ['surprised'],
  '😲': ['astonished'],
  '😳': ['flushed'],
  '🥺': ['pleading', 'please'],
  '😦': ['frowning mouth'],
  '😧': ['anguished'],
  '😨': ['fearful'],
  '😰': ['anxious sweat'],
  '😥': ['sad sweat'],
  '😢': ['crying'],
  '😭': ['sobbing', 'cry'],
  '😱': ['screaming', 'scared'],
  '😖': ['confounded'],
  '😣': ['persevering'],
  '😞': ['disappointed'],
  '😓': ['downcast sweat'],
  '😩': ['weary'],
  '😫': ['tired'],
  '🥱': ['yawning'],
  '😤': ['triumph', 'angry'],
  '😡': ['angry'],
  '😠': ['rage'],
  '🤬': ['cursing', 'swear'],
  '😈': ['devil'],
  '👿': ['angry devil'],
  '💀': ['skull', 'dead'],
  '☠️': ['skull and crossbones'],
  '💩': ['poop'],
  '🤡': ['clown'],
  '👹': ['ogre'],
  '👺': ['goblin'],
  '👻': ['ghost'],
  '👽': ['alien'],
  '👾': ['space invader'],
  '🤖': ['robot'],
  '😺': ['cat smile'],
  '😸': ['cat grin'],
  '😹': ['cat tears of joy'],
  '😻': ['cat heart eyes'],
  '😼': ['cat smirk'],
  '😽': ['cat kiss'],
  '🙀': ['cat scream'],
  '😿': ['cat crying'],
  '😾': ['cat pouting'],
  '❤️': ['red heart', 'love'],
  '🧡': ['orange heart'],
  '💛': ['yellow heart'],
  '💚': ['green heart'],
  '💙': ['blue heart'],
  '💜': ['purple heart'],
  '🖤': ['black heart'],
  '🤍': ['white heart'],
  '🤎': ['brown heart'],
  '💔': ['broken heart'],
  '❣️': ['heart exclamation'],
  '💕': ['two hearts'],
  '💞': ['revolving hearts'],
  '💓': ['beating heart'],
  '💗': ['growing heart'],
  '💖': ['sparkling heart'],
  '💘': ['cupid heart'],
  '💝': ['heart box'],
  '💟': ['heart decoration'],
  '☮️': ['peace'],
  '✝️': ['cross'],
  '☪️': ['star and crescent'],
  '🕉️': ['om'],
  '☸️': ['dharma wheel'],
  '✡️': ['star of david'],
  '🔯': ['six pointed star'],
  '🕎': ['menorah'],
  '☯️': ['yin yang'],
  '☦️': ['orthodox cross'],
  '🛐': ['place of worship'],
  '⛎': ['ophiuchus'],
  '♈': ['aries'],
  '♉': ['taurus'],
  '♊': ['gemini'],
  '♋': ['cancer'],
  '♌': ['leo'],
  '♍': ['virgo'],
  '♎': ['libra'],
  '♏': ['scorpio'],
  '♐': ['sagittarius'],
  '♑': ['capricorn'],
  '♒': ['aquarius'],
  '♓': ['pisces'],
  '🆔': ['id'],
  '⚛️': ['atom'],
  '🉑': ['accept'],
  '☢️': ['radioactive'],
  '☣️': ['biohazard'],
  '📴': ['mobile off'],
  '📳': ['vibration'],
  '🈶': ['not free'],
  '🈚': ['free'],
  '🈸': ['application'],
  '🈺': ['open for business'],
  '🈷️': ['monthly'],
  '✴️': ['eight pointed star'],
  '🆚': ['versus'],
  '💮': ['white flower'],
  '🉐': ['bargain'],
  '㊙️': ['secret'],
  '㊗️': ['congratulations'],
  '🈴': ['passing grade'],
  '🈵': ['no vacancy'],
  '🈹': ['discount'],
  '🈲': ['prohibited'],
  '🅰️': ['a button'],
  '🅱️': ['b button'],
  '🆎': ['ab button'],
  '🆑': ['cl button'],
  '🅾️': ['o button'],
  '🆘': ['sos'],
  '❌': ['cross mark'],
  '⭕': ['circle'],
  '🛑': ['stop'],
  '⛔': ['no entry'],
  '📛': ['name badge'],
  '🚫': ['prohibited'],
  '💯': ['hundred'],
  '💢': ['anger'],
  '♨️': ['hot springs'],
  '🚷': ['no pedestrians'],
  '🚯': ['no littering'],
  '🚳': ['no bicycles'],
  '🚱': ['non potable water'],
  '🔞': ['underage'],
  '📵': ['no mobile'],
  '🚭': ['no smoking'],
  '❗': ['exclamation'],
  '❕': ['exclamation mark'],
  '❓': ['question'],
  '❔': ['question mark'],
  '‼️': ['double exclamation'],
  '⁉️': ['question exclamation'],
  '🔅': ['dim'],
  '🔆': ['bright'],
  '〽️': ['part alternation'],
  '⚠️': ['warning'],
  '🚸': ['children crossing'],
  '🔱': ['trident'],
  '⚜️': ['fleur de lis'],
  '🔰': ['beginner'],
  '♻️': ['recycling'],
  '✅': ['check mark'],
  '🈯': ['reserved'],
  '💹': ['chart increasing'],
  '❇️': ['sparkle'],
  '✳️': ['eight spoked asterisk'],
  '❎': ['cross mark button'],
  '🌐': ['globe'],
  '💠': ['diamond shape'],
  'Ⓜ️': ['metro'],
  '🌀': ['cyclone'],
  '💤': ['zzz'],
  '🏧': ['atm'],
  '🚾': ['water closet'],
  '♿': ['wheelchair'],
  '🅿️': ['parking'],
  '🈳': ['vacancy'],
  '🈂️': ['service charge'],
  '🛂': ['passport control'],
  '🛃': ['customs'],
  '🛄': ['baggage claim'],
  '🛅': ['left luggage'],
  '🚹': ['men'],
  '🚺': ['women'],
  '🚼': ['baby'],
  '⚧️': ['transgender'],
  '🚻': ['restroom'],
  '🚮': ['litter'],
  '🎦': ['cinema'],
  '📶': ['signal'],
  '🈁': ['here'],
  '🔣': ['symbols'],
  'ℹ️': ['information'],
  '🔤': ['abc'],
  '🔡': ['abcd'],
  '🔠': ['capitals'],
  '🆖': ['ng'],
  '🆗': ['ok'],
  '🆙': ['up'],
  '🆒': ['cool'],
  '🆕': ['new'],
  '🆓': ['free'],
  '0️⃣': ['zero'],
  '1️⃣': ['one'],
  '2️⃣': ['two'],
  '3️⃣': ['three'],
  '4️⃣': ['four'],
  '5️⃣': ['five'],
  '6️⃣': ['six'],
  '7️⃣': ['seven'],
  '8️⃣': ['eight'],
  '9️⃣': ['nine'],
  '🔟': ['ten'],
  '👍': ['thumbs up', 'like'],
  '👎': ['thumbs down', 'dislike'],
  '👋': ['wave', 'hello', 'bye'],
  '🤚': ['raised hand'],
  '🖐️': ['hand with fingers'],
  '✋': ['raised hand'],
  '🖖': ['vulcan salute'],
  '👌': ['ok hand', 'okay'],
  '🤌': ['pinched fingers'],
  '🤏': ['pinching hand'],
  '✌️': ['peace'],
  '🤞': ['crossed fingers', 'luck'],
  '🤟': ['love you'],
  '🤘': ['rock on'],
  '🤙': ['call me'],
  '👈': ['backhand left'],
  '👉': ['backhand right'],
  '👆': ['backhand up'],
  '🖕': ['middle finger'],
  '👇': ['backhand down'],
  '☝️': ['index up'],
  '✊': ['raised fist'],
  '👊': ['fist bump'],
  '🤛': ['left fist'],
  '🤜': ['right fist'],
  '👏': ['clapping', 'applause'],
  '🙌': ['raising hands'],
  '👐': ['open hands'],
  '🤲': ['palms together'],
  '🤝': ['handshake', 'deal'],
  '🙏': ['pray', 'please'],
  '✍️': ['writing'],
  '💅': ['nail polish', 'slay'],
  '🤳': ['selfie'],
  '💪': ['muscle', 'strong'],
  '🦾': ['mechanical arm'],
  '🦿': ['mechanical leg'],
  '🦵': ['leg'],
  '🦶': ['foot'],
  '👂': ['ear'],
  '🦻': ['ear with hearing aid'],
  '👃': ['nose'],
  '🧠': ['brain'],
  '🫀': ['anatomical heart'],
  '🫁': ['lungs'],
  '🦷': ['tooth'],
  '🦴': ['bone'],
  '👀': ['eyes', 'look'],
  '👁️': ['eye'],
  '👅': ['tongue'],
  '👄': ['mouth'],
  '🔥': ['fire', 'lit'],
  '💧': ['droplet'],
  '💦': ['sweat droplets'],
  '🌊': ['wave'],
  '🎉': ['party popper', 'celebrate'],
  '🎊': ['confetti'],
  '🎈': ['balloon'],
  '🎁': ['gift'],
  '🏆': ['trophy', 'win'],
  '🥇': ['gold medal', 'first'],
  '🥈': ['silver medal', 'second'],
  '🥉': ['bronze medal', 'third'],
  '⚽': ['soccer ball'],
  '⚾': ['baseball'],
  '🥎': ['softball'],
  '🏀': ['basketball'],
  '🏐': ['volleyball'],
  '🏈': ['football'],
  '🏉': ['rugby'],
  '🎾': ['tennis'],
  '🥏': ['flying disc'],
  '🎳': ['bowling'],
  '🏏': ['cricket'],
  '🏑': ['field hockey'],
  '🏒': ['ice hockey'],
  '🥍': ['lacrosse'],
  '🏓': ['ping pong'],
  '🏸': ['badminton'],
  '🥊': ['boxing glove', 'fight'],
  '🥋': ['martial arts'],
  '🥅': ['goal'],
  '⛳': ['flag in hole', 'golf'],
  '⛸️': ['ice skate'],
  '🎣': ['fishing pole'],
  '🤿': ['diving mask'],
  '🎽': ['running shirt'],
  '🎿': ['skis'],
  '🛷': ['sled'],
  '🥌': ['curling stone'],
  '🎯': ['bullseye'],
  '🪀': ['yo-yo'],
  '🪁': ['kite'],
  '🎱': ['pool ball'],
  '🔮': ['crystal ball'],
  '🪄': ['magic wand'],
  '🧿': ['nazar amulet'],
  '🎮': ['video game'],
  '🕹️': ['joystick'],
  '🎰': ['slot machine'],
  '🎲': ['dice'],
  '🧩': ['puzzle piece'],
  '🧸': ['teddy bear'],
  '🪅': ['pinata'],
  '🪆': ['nesting dolls'],
  '♠️': ['spade'],
  '♥️': ['heart suit'],
  '♦️': ['diamond suit'],
  '♣️': ['club suit'],
  '♟️': ['chess pawn'],
  '🃏': ['joker'],
  '🀄': ['mahjong'],
  '🎴': ['flower cards'],
  '🎭': ['performing arts'],
  '🖼️': ['framed picture'],
  '🎨': ['artist palette'],
  '🧵': ['thread'],
  '🪡': ['sewing needle'],
  '🧶': ['yarn'],
  '🪢': ['knot'],
  '🍕': ['pizza'],
  '🍔': ['burger'],
  '🍟': ['fries'],
  '🌭': ['hot dog'],
  '🍿': ['popcorn'],
  '🧈': ['butter'],
  '🧂': ['salt'],
  '🥚': ['egg'],
  '🍳': ['cooking'],
  '🧇': ['waffle'],
  '🥞': ['pancakes'],
  '🧀': ['cheese'],
  '🍖': ['meat'],
  '🍗': ['poultry'],
  '🥩': ['steak'],
  '🥓': ['bacon'],
  '🌮': ['taco'],
  '🌯': ['burrito'],
  '🥙': ['stuffed flatbread'],
  '🥘': ['paella'],
  '🍲': ['pot of food'],
  '🥣': ['bowl with spoon'],
  '🥗': ['salad'],
  '🥫': ['canned food'],
  '🍱': ['bento'],
  '🍘': ['rice cracker'],
  '🍙': ['rice ball'],
  '🍚': ['cooked rice'],
  '🍛': ['curry'],
  '🍜': ['steaming bowl'],
  '🍝': ['spaghetti'],
  '🍠': ['roasted sweet potato'],
  '🍢': ['oden'],
  '🍣': ['sushi'],
  '🍤': ['fried shrimp'],
  '🍥': ['fish cake'],
  '🥮': ['moon cake'],
  '🍡': ['dango'],
  '🥟': ['dumpling'],
  '🥠': ['fortune cookie'],
  '🥡': ['takeout box'],
  '🦀': ['crab'],
  '🦞': ['lobster'],
  '🦐': ['shrimp'],
  '🦑': ['squid'],
  '🦪': ['oyster'],
  '🍦': ['ice cream'],
  '🍧': ['shaved ice'],
  '🍨': ['ice cream'],
  '🍩': ['donut'],
  '🍪': ['cookie'],
  '🎂': ['birthday cake'],
  '🍰': ['cake'],
  '🧁': ['cupcake'],
  '🥧': ['pie'],
  '🍫': ['chocolate'],
  '🍬': ['candy'],
  '🍭': ['lollipop'],
  '🍮': ['custard'],
  '🍯': ['honey'],
  '🍼': ['baby bottle'],
  '🥛': ['milk'],
  '☕': ['coffee'],
  '🫖': ['teapot'],
  '🍵': ['tea'],
  '🍶': ['sake'],
  '🍾': ['champagne'],
  '🍷': ['wine'],
  '🍸': ['cocktail'],
  '🍹': ['tropical drink'],
  '🍺': ['beer'],
  '🍻': ['beers'],
  '🥂': ['clinking glasses'],
  '🥃': ['tumbler'],
  '🥤': ['cup with straw'],
  '🧋': ['bubble tea'],
  '🧃': ['juice box'],
  '🧉': ['mate'],
  '🧊': ['ice'],
  '🫠': ['melting face'],
  '🫡': ['saluting face'],
  '🫢': ['gasping face'],
  '🫣': ['peeking face'],
  '🫤': ['face with diagonal mouth'],
  '🫥': ['dotted line face'],
  '🫨': ['shaking face'],
  '🥹': ['holding back tears'],
  '🫶': ['heart hands'],
  '🫰': ['money gesture'],
  '🫷': ['left pushing hand'],
  '🫸': ['right pushing hand'],
  '🫳': ['palm down hand'],
  '🫴': ['palm up hand'],
  '🫱': ['rightward hand'],
  '🫲': ['leftward hand'],
  '🩷': ['pink heart'],
  '🩵': ['light blue heart'],
  '🩶': ['gray heart'],
  '🦭': ['seal'],
  '🪿': ['goose'],
  '🦤': ['dodo'],
  '🦫': ['beaver'],
  '🦦': ['otter'],
  '🦨': ['skunk'],
  '🦩': ['flamingo'],
  '🦮': ['guide dog'],
  '🐕‍🦺': ['service dog'],
  '🐈‍⬛': ['black cat'],
  '🪱': ['worm'],
  '🪰': ['fly'],
  '🪳': ['cockroach'],
  '🪲': ['beetle'],
  '🪶': ['feather'],
  '🪸': ['coral'],
  '🪷': ['lotus'],
  '🪻': ['hyacinth'],
  '🪴': ['potted plant'],
  '🫛': ['peas'],
  '🫘': ['beans'],
  '🫕': ['fondue'],
  '🫓': ['flatbread'],
  '🧆': ['falafel'],
  '🫔': ['tamale'],
  '🧄': ['garlic'],
  '🧅': ['onion'],
  '🫐': ['blueberries'],
  '🫒': ['olive'],
  '🫚': ['ginger'],
  '🫗': ['pouring liquid'],
  '🦰': ['red hair'],
  '🦱': ['curly hair'],
  '🦳': ['white hair'],
  '🦲': ['bald'],
  '🫦': ['biting lip'],
  '🩸': ['blood drop'],
  '🩹': ['adhesive bandage'],
  '🩼': ['crutch'],
  '🦽': ['manual wheelchair'],
  '🦼': ['motorized wheelchair'],
  '🩻': ['x-ray'],
  '🧢': ['cap'],
  '🪖': ['military helmet'],
  '🧣': ['scarf'],
  '🧤': ['gloves'],
  '🧥': ['coat'],
  '🧦': ['socks'],
  '🥾': ['hiking boot'],
  '🥿': ['flat shoe'],
  '👗': ['dress'],
  '👕': ['tshirt'],
  '🩲': ['briefs'],
  '🩳': ['shorts'],
  '🩴': ['flip flops'],
  '🪮': ['comb'],
  '🪭': ['folding fan'],
  '🕶️': ['sunglasses'],
  '🛻': ['pickup truck'],
  '🚛': ['truck'],
  '🛞': ['wheel'],
  '🛺': ['auto rickshaw'],
  '🛩️': ['small airplane'],
  '🪂': ['parachute'],
  '🛸': ['ufo'],
  '🚀': ['rocket'],
  '🛰️': ['satellite'],
  '🪐': ['planet'],
  '🌌': ['milky way'],
  '🪨': ['rock'],
  '🪵': ['log'],
  '🛖': ['hut'],
  '🛕': ['hindu temple'],
  '🕌': ['mosque'],
  '🕋': ['kaaba'],
  '🪣': ['bucket'],
  '🪠': ['plunger'],
  '🪩': ['disco ball'],
  '🪞': ['mirror'],
  '🪟': ['window'],
  '🪑': ['chair'],
  '🛋️': ['sofa'],
  '🛏️': ['bed'],
  '🪤': ['mouse trap'],
  '🪒': ['razor'],
  '🪫': ['low battery'],
  '🪪': ['id card'],
  '🧯': ['fire extinguisher'],
  '🧰': ['toolbox'],
  '🪓': ['axe'],
  '🖲️': ['trackball'],
  '🧭': ['compass'],
  '🕰️': ['mantel clock'],
  '📸': ['camera flash'],
  '📹': ['video camera'],
  '🧮': ['abacus'],
  '🧾': ['receipt'],
  '🪙': ['coin'],
  '🌪️': ['tornado'],
  '🌫️': ['fog'],
  '🫧': ['bubbles'],
  '🌡️': ['thermometer'],
  '🌦️': ['sun behind rain cloud'],
  '🌨️': ['snow cloud'],
  '🌩️': ['lightning cloud'],
  '🌈': ['rainbow'],
  '🪹': ['empty nest'],
  '🪺': ['nest with eggs'],
  '🪼': ['jellyfish'],
  '🪯': ['khanda'],
  '🫱🏽': ['rightward hand'],
  '🫲🏿': ['leftward hand'],
  '🫶🏻': ['heart hands'],
  '🏳️': ['white flag'],
  '🏴': ['black flag'],
  '🏳️‍🌈': ['rainbow flag'],
  '🏳️‍⚧️': ['transgender flag'],
  '🇮🇳': ['india flag'],
  '🇺🇸': ['usa flag'],
  '🇫🇷': ['france flag'],
  '🇯🇵': ['japan flag'],
  '🇨🇦': ['canada flag'],
  '🇩🇪': ['germany flag'],
  '🇬🇧': ['uk flag']
};

// Create reverse mapping (word to emoji)
export const wordToEmoji: Record<string, string> = Object.entries(emojiToWord).reduce(
  (acc, [emoji, words]) => {
    words.forEach(word => {
        acc[word.toLowerCase()] = emoji;
    });
    return acc;
  },
  {} as Record<string, string>
);

// Helper for regex escaping
const escapeRegExp = (string: string) => string.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');

// Pre-compute regex for performance - matches longest phrases first
const emojiKeywords = Object.keys(wordToEmoji).sort((a, b) => b.length - a.length);
// Use word boundaries to prevent partial matches (e.g. "hot" matching inside "hotel")
const emojiPattern = new RegExp(`\\b(${emojiKeywords.map(escapeRegExp).join('|')})\\b`, 'gi');

// Translate text to emojis
export const translateToEmojis = (text: string): string => {
  if (!text.trim()) return '';

  return text.replace(emojiPattern, (match) => {
    return wordToEmoji[match.toLowerCase()];
  });
};

// Translate emojis to text
export const translateToWords = (text: string): string => {
  if (!text.trim()) return '';

  // Match emojis using regex
  const emojiRegex = /[\u{1F300}-\u{1F9FF}]|[\u{2600}-\u{26FF}]|[\u{2700}-\u{27BF}]/gu;

  return text.replace(emojiRegex, (emoji) => {
    const words = emojiToWord[emoji];
    return words && words.length > 0 ? ` ${words[0]} ` : emoji;
  }).replace(/\s+/g, ' ').trim();
};
